from util import generate_file

INPUT_JSON = {"model": {
  "rsPaymentDate": {
    "1": [
      "2021-04-01T21:00:00.000Z",
      "2021-04-07T21:00:00.000Z"
    ]
  },
  "rsPaymentDateFL": {
    "1": [
      "2021-04-05T21:00:00.000Z",
      "2021-04-12T21:00:00.000Z"
    ],
    "2": [
      "2021-04-20T21:00:00.000Z",
      "2021-04-22T21:00:00.000Z"
    ]
  },
  "rsPayment": {
    "1": "10000"
},
  "rsPaymentFL": {
    "1": "1000",
    "2": "1000"
  },
  "sellerFullName": "Карих Виктор Абзалович",
  "sellerBirthYear": "",
  "sellerBirthPlace": "Москва",
  "sellerNationality": "Российская Федерация",
  "sellerPassNumberFirst": "4532",
  "sellerPassNumberSec": "4434565",
  "sellerPassIssuedBy": "ОТДЕЛОМ УФМС РОССИИ ПО ГОР.МОСКВЕ В ЕБЕНЯХ",
  "sellerPassIssuedOn": "",
  "sellerUnitCode": "336774",
  "sellerRegAddress": "Москва, Хохловский пер.,д.7",
  "sellerOrgLegalForm": "Общество с ограниченной ответственностью",
  "sellerOrgName": "Яйцеглот",
  "sellerCeoFullName": "Яйцеглота Вячеслава Геннадиевича",
  "sellerOrgPossition": "помощника генерального директора",
  "sellerOrgDoc": "доверенности",
  "sellerOrgDocNum": "69",
  "sellerOrgDocDate": "",
  "custFullName": "Яйцеглот Вячеслав Геннадиевич",
  "custBirthYear": "",
  "custBirthPlace": "Москва",
  "custNationality": "Российская Федерация",
  "custPassNumberFirst": "4444",
  "custPassNumberSec": "333333",
  "custPassIssuedBy": "ОТДЕЛОМ УФМС РОССИИ ПО ГОР.МОСКВЕ В ЕБЕНЯХ",
  "custPassIssuedOn": "",
  "custUnitCode": "443222",
  "custRegAddress": "Москва, Грачевский пер.,д.7",
  "custOrgLegalForm": "ООО",
  "custOrgName": "ЯЙЦЕГЛОТ",
  "custOrgPossition": "помощник руководителя",
  "custCeoFullName": "",
  "custOrgDoc": "",
  "custOrgDocNum": "",
  "custOrgDocDate": "",
  "email": "example@gmail.com",
  "date": "",
  "city": "Город в котором заключается договор",
  "propertyName": "",
  "propertyAddress": "Москва, Грачевский пер.,д.7",
  "propertyFloorArea": "3",
  "propertyNumRoom": "3",
  "propertyLevel": "3",
  "propertyUniqueIdentifier": "122132432423423",
  "propertyDoc": "",
  "propertyRegObl": "",
  "propertyLandCat": "",
  "propertyLandUsed": "",
  "regDocNumber": "",
  "regDocDate": "",
  "cost": "",
  "payMethod": [
    {
      "id": "Рассрочка",
      "name": "Рассрочка"
    },
    {
      "id": "Аккредитив",
      "name": "Аккредитив"
    },
    {
      "id": "Ипотека физ. лица",
      "name": "Ипотека физ. лица"
    }
  ],
  "paySumMatCap": "",
  "paySumRS": "1000",
  "paySumIB": "",
  "paySumIF": "",
  "paySumA": "",
  "matcap": "",
  "matcapDesDate": "",
  "matcapDesNum": "",
  "matcapSer": "",
  "matcapNum": "",
  "matcapDate": "",
  "matcapOwner": "",
  "quantityPayments": "1",
  "crBankName": "",
  "crBankNumber": "",
  "crBankDocDate": "",
  "crBankDocTown": "",
  "crBankDocQMonth": "",
  "crBankOgrn": "",
  "crBankInn": "",
  "crBankKpp": "",
  "crBankRs": "",
  "crBankKs": "",
  "crBankBik": "",
  "crBankAddress": "",
  "crBankPostAddress": "",
  "acrDays": "45",
  "acrBankName": "Сбербанк",
  "acrBankTown": "Москва",
  "acrBankSellerNumber": "323223323223",
  "acrBankSellerName": "Карих Виктор",
  "sellerOrgDocPassNumFirst": "3333",
  "sellerOrgDocPassNumSec": "44444555",
  "zlgPayTermDate": "2021-04-07T21:00:00.000Z",
  "quantityPaymentsFL": "2",
  "nal": "",
  "bznal": "",
  "bznalBankNum": "",
  "bznalBankName": "",
  "sellerOrgDocPassDate": "",
  "sellerOrgUnitCode": "",
  "sellerOrgRegAddress": "",
  "custOrgDocPassNumFirst": "",
  "custOrgDocPassNumSec": "",
  "custOrgPassIssuedBy": "",
  "custOrgDocPassDate": "",
  "custOrgUnitCode": "112234",
  "custOrgRegAddress": "Москва, Хохловский пер.,д.7",
  "custOrgRegAddressUR": "Москва, Хохловский пер.,д.7",
  "custOrgOGRN": "3223323223",
  "custOrgINN": "323223",
  "custOrgKPP": "32323232",
  "custOrgRS": "32323232",
  "custOrgKS": "32233232",
  "custOrgBankBik": "3322332",
  "custOrgBank": "ТИНЬКОФФ",
  "custOrgTel": "123456789",
  "custOrgPostAddress": "Москва, Хохловский пер.,д.7",
  "sellerOrgRegAddressUR": "Москва, Хохловский пер.,д.7",
  "sellerOrgOGRN": "777777",
  "sellerOrgINN": "66666",
  "sellerOrgKPP": "55555",
  "sellerOrgRS": "444444",
  "sellerOrgKS": "3333333",
  "sellerOrgBank": "22222222",
  "sellerOrgBankBik": "11111111",
  "sellerOrgTel": "50543003987",
  "sellerOrgPostAddress": "Москва, Грачевский пер.,д.7",
  "zlgPay": "Не имеется",
  "paySumFL": "10000"
},
    "select_first_step": "Договор купли-продажи недвижимого имущества", "select_second_step": "ФЛ",
    "select_third_step": "ЮЛ"
}

generate_file(INPUT_JSON)